import './globals.css'
import type { Metadata } from 'next'

import 'bootstrap/dist/css/bootstrap.min.css'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/03244eb91d.js" crossorigin="anonymous"></script>
      </head>
      <body>{children}</body>
    </html>
  )
}
